version: 2

builds:
  - env:
      - CGO_ENABLED=0
      - GOCACHE=/tmp/go-cache
      - GOMODCACHE=/tmp/go-mod-cache
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils.PackageName=sbercloud
    goos: [linux, darwin, windows, freebsd]
    goarch: [amd64, arm64, '386']
    ignore:
      - goos: darwin
        goarch: '386'
    binary: terraform-provider-sbercloud_v{{ .Version }}

archives:
  - format: zip
    name_template: terraform-provider-sbercloud_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: terraform-provider-sbercloud_{{ .Version }}_SHA256SUMS

signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  draft: true